function buildFabricModJson(namespace, name) {
  return {
    schemaVersion: 1,
    id: namespace,
    version: '1.0.0',
    name,
    description: `${name} generated by MC Studio`,
    environment: '*',
    entrypoints: {
      main: [`${namespace}.${namespace}Mod`]
    },
    depends: {
      minecraft: '1.20.1',
      fabricloader: '>=0.15.0',
      fabric: '*',
      java: '>=17'
    }
  };
}

function buildFabricMainClass(namespace) {
  return `package ${namespace};

import net.fabricmc.api.ModInitializer;

public class ${namespace}Mod implements ModInitializer {
    @Override
    public void onInitialize() {
    }
}
`;
}

module.exports = { buildFabricModJson, buildFabricMainClass };
